### ISSUE TITLE
Create an HTML page where the manager could see employee details associated with him.

### ISSUE THREAD

**Issue by akgaur05** [nyramirez/Threat-Alert-P1#5]
Create a page where the manager can see the employee data and can add/remove or edit employee.
Initially, the page will show only employee data and a form where a new employee can be added. On click of any row fields get fill into input boxes and you can edit or delete data.

**Comment by nyramirez** [comment]
the page to see the list of employees per manager is done. We can also use this page as the alert for the manager in ase of any issues. Next, I am working on the page for each employee information.
